// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_the_wild_ones = "CgkIuab0_LYfEAIQDQ"; // <GPGSID>
        public const string achievement_starlight_glimmer = "CgkIuab0_LYfEAIQDA"; // <GPGSID>
        public const string achievement_god_of_war = "CgkIuab0_LYfEAIQAg"; // <GPGSID>
        public const string achievement_united_we_stand = "CgkIuab0_LYfEAIQBw"; // <GPGSID>
        public const string achievement_master_fighter = "CgkIuab0_LYfEAIQAQ"; // <GPGSID>
        public const string achievement_the_purple_six = "CgkIuab0_LYfEAIQDw"; // <GPGSID>
        public const string achievement_the_deadly_few = "CgkIuab0_LYfEAIQBQ"; // <GPGSID>
        public const string achievement_the_wolf_pack = "CgkIuab0_LYfEAIQCg"; // <GPGSID>
        public const string achievement_the_team_stars_fell_on = "CgkIuab0_LYfEAIQCA"; // <GPGSID>
        public const string achievement_the_mighty_host = "CgkIuab0_LYfEAIQBA"; // <GPGSID>
        public const string achievement_nonstop_to_the_top = "CgkIuab0_LYfEAIQBg"; // <GPGSID>
        public const string achievement_just_like_old_times = "CgkIuab0_LYfEAIQCQ"; // <GPGSID>
        public const string achievement_hyper_rookie = "CgkIuab0_LYfEAIQCw"; // <GPGSID>
        public const string achievement_hyper_veteran = "CgkIuab0_LYfEAIQAw"; // <GPGSID>

}

